from raw_data_processing.docs_parsers.parsers.base import BaseParser
from raw_data_processing.docs_parsers.parsers.entities import DocType, ParsingScheme
from raw_data_processing.docs_parsers.parsers.pdf import PDFParser
from raw_data_processing.docs_parsers.parsers.word_doc import WordDocumentParser
