ENV_PREFIX = "PROTO_LLM"
ENV_VAR_LLM_API_HOST = f"{ENV_PREFIX}_LLM_API_HOST"
ENV_VAR_LLM_API_PORT = f"{ENV_PREFIX}_LLM_API_PORT"

ENV_VAR_TEXT_EMB_HOST = f"{ENV_PREFIX}_TEXT_EMB_HOST"
ENV_VAR_TEXT_EMB_PORT = f"{ENV_PREFIX}_TEXT_EMB_PORT"

ENV_VAR_REDIS_HOST = f"{ENV_PREFIX}_REDIS_HOST"
ENV_VAR_REDIS_PORT = f"{ENV_PREFIX}_REDIS_PORT"

ENV_VAR_RABBIT_PORT = f"{ENV_PREFIX}_RABBIT_PORT"
ENV_VAR_RABBIT_HOST = f"{ENV_PREFIX}_RABBIT_HOST"

ENV_VAR_RABBIT_USER = f"{ENV_PREFIX}_RABBIT_USER"
ENV_VAR_RABBIT_PASSWORD = f"{ENV_PREFIX}_RABBIT_PASSWORD"

ENV_VAR_VECTOR_PORT = f"{ENV_PREFIX}_VECTOR_PORT"
ENV_VAR_VECTOR_HOST = f"{ENV_PREFIX}_VECTOR_HOST"

ENV_VAR_CELERY_QUEUE = f"{ENV_PREFIX}_CELERY_QUEUE_NAME"

ENV_VAR_JOB_INVOCATION_TYPE = f"{ENV_PREFIX}_JOB_INVOCATION_TYPE"
