version: '3.5'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - 5672:${RABBITMQ_PORT:-5672}
      - 15672:${RABBITMQ_MANAGEMENT_PORT:-15672}
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER:-protollm_user}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS:-super_secure_pass_123}
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"
    networks:
      - llm_wrap_network

  redis:
    image: "redis:alpine"
    ports:
      - 6379:${REDIS_PORT:-6379}
    volumes:
      - redis_data:/var/lib/data
    networks:
      - llm_wrap_network

  celery_worker:
    build:
      context: ../../
      dockerfile: deployment/sdk-base/Dockerfile
    depends_on:
      - rabbitmq
      - redis
    networks:
      - llm_wrap_network
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL:-amqp://protollm_user:super_secure_pass_123@rabbitmq:5672/}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND:-redis://redis:6379/0}
      - C_FORCE_ROOT=True
      - LLM_API_HOST=${LLM_API_HOST:-localhost}
      - LLM_API_PORT=${LLM_API_PORT:-6672}
      - TEXT_EMB_HOST=${TEXT_EMB_HOST:-embedding_server}
      - TEXT_EMB_PORT=${TEXT_EMB_PORT:-80}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - RABBIT_HOST=${RABBIT_HOST:-rabbitmq}
      - RABBIT_PORT=${RABBIT_PORT:-5672}
      - VECTOR_HOST=${VECTOR_HOST:-localhost}
      - VECTOR_PORT=${VECTOR_PORT:-9941}
    command: celery -A protollm_sdk.celery.app worker --loglevel=info

  flower:
    build:
      context: ../../
      dockerfile: deployment/sdk-base/Dockerfile
    ports:
      - 7672:${FLOWER_PORT:-7672}
    depends_on:
      - rabbitmq
      - celery_worker
    networks:
      - llm_wrap_network
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL:-amqp://default_user:super_secure_pass_123@rabbitmq:5672/}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND:-redis://redis:6379/0}
      - LLM_API_HOST=${LLM_API_HOST:-localhost}
      - LLM_API_PORT=${LLM_API_PORT:-6672}
      - TEXT_EMB_HOST=${TEXT_EMB_HOST:-embedding_server}
      - TEXT_EMB_PORT=${TEXT_EMB_PORT:-80}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - RABBIT_HOST=${RABBIT_HOST:-rabbitmq}
      - RABBIT_PORT=${RABBIT_PORT:-5672}
      - VECTOR_HOST=${VECTOR_HOST:-localhost}
      - VECTOR_PORT=${VECTOR_PORT:-9941}
    command: sh -c "sleep 20 && celery -A protollm_sdk.celery.app flower --broker=amqp://protollm_user:super_secure_pass_123@rabbitmq:5672/ --port=7672"

  server:
    image: chromadb/chroma:latest
    environment:
      - IS_PERSISTENT=${IS_PERSISTENT:-TRUE}
    ports:
      - 9941:${SERVER_PORT:-8000}
    networks:
      - llm_wrap_network

  embedding_server:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-0.3.0
    command: --model-id ${ST_MODEL:-intfloat/multilingual-e5-large} --revision main
    ports:
      - 9942:${EMBEDDING_SERVER_PORT:-80}
    networks:
      - llm_wrap_network

volumes:
  rabbitmq_data:
  redis_data:

networks:
  llm_wrap_network:
    name: llm_wrap_network
    driver: bridge
